In [1]:
import numpy as np

In [2]:
a = np.arange(4).reshape(2,2)

In [3]:
a

array([[0, 1],
       [2, 3]])

In [4]:
b = np.arange(3,7).reshape(2,2)

In [5]:
b

array([[3, 4],
       [5, 6]])

In [6]:
a + b

array([[3, 5],
       [7, 9]])

In [7]:
a.T

array([[0, 2],
       [1, 3]])

In [8]:
a.T + b

array([[3, 6],
       [6, 9]])

In [9]:
a - b

array([[-3, -3],
       [-3, -3]])

In [10]:
np.dot(a,b)

array([[ 5,  6],
       [21, 26]])

In [11]:
v = np.array([10,20])

In [12]:
np.dot(a,v)

array([20, 80])

In [13]:
np.dot(v,a)

array([40, 70])