In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
y = np.array([4,5,6])

In [4]:
X,Y = np.meshgrid(x,y)

In [5]:
X

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [6]:
Y

array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [7]:
X.ravel()

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [8]:
Y.ravel()

array([4, 4, 4, 5, 5, 5, 6, 6, 6])