In [1]:
import numpy as np

In [2]:
v = np.arange(10,15)

In [3]:
v

array([10, 11, 12, 13, 14])

In [4]:
v[2:4]

array([12, 13])

In [5]:
v[:3]

array([10, 11, 12])

In [6]:
v[3:]

array([13, 14])

In [7]:
v[:-1]

array([10, 11, 12, 13])

In [8]:
a = np.arange(1,5).reshape(2,2)

In [9]:
a

array([[1, 2],
       [3, 4]])

In [10]:
u = a[0,:]

In [11]:
u

array([1, 2])

In [12]:
u = a[:,1]

In [13]:
u

array([2, 4])

In [14]:
ii = np.array([2,3])

In [15]:
v[ii]

array([12, 13])

In [16]:
w = np.array([False,False,False,True,True])

In [17]:
v[w]

array([13, 14])

In [18]:
a * 2

array([[2, 4],
       [6, 8]])

In [19]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [20]:
v < 13

array([ True,  True,  True, False, False])

In [21]:
v[v<13]

array([10, 11, 12])