In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3)

In [3]:
b = np.arange(6,12).reshape(2,3)

In [4]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
np.c_[a,b]

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [7]:
np.r_[a,b]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
c = np.arange(3)

In [9]:
d = np.arange(3,6)

In [10]:
c

array([0, 1, 2])

In [11]:
d

array([3, 4, 5])

In [12]:
np.c_[c,d]

array([[0, 3],
       [1, 4],
       [2, 5]])

In [13]:
np.r_[c,d]

array([0, 1, 2, 3, 4, 5])