In [1]:
import numpy as np

In [2]:
from scipy import sparse

In [3]:
a = sparse.lil_matrix((5,5))

In [4]:
a[0,0]=1; a[1,2]=2; a[3,4]=3; a[4,4]=4

In [5]:
a

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in LInked List format>

In [6]:
a.todense()

matrix([[1., 0., 0., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 3.],
        [0., 0., 0., 0., 4.]])

In [7]:
b = a.tocsr()

In [8]:
b

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [9]:
b.getrow(1).todense()

matrix([[0., 0., 2., 0., 0.]])

In [10]:
v = np.array([1,2,3,4,5])

In [11]:
a.dot(v)

array([ 1.,  6.,  0., 15., 20.])